### PR TITLE
Add a startup script to automate cabling process

### LINKED ISSUE #41: Automate cabling process
Discussed with @KylerBurke and @jinaloo7, we could have a script to automate the creation of cables. The pattern that we agree on is all the 1-2 ports go to efr1, and 3-4 goes to efr2.

### PR DESCRIPTION
**Pull request by hoanhan101**
Fixes #41

### CODE REVIEW

**Comment by marcoceppi** [comment]
We use `SKIP_STARTUP_SCRIPTS=False` to skip startup scripts in general and also use manifests to define initalizer yamls but since this has no yaml initializer if we ever flip `SKIP_STARTUP_SCRIPTS` to True it's going to attempt to cable/recable things as we can't inject configuration via an initializer yaml

**Comment by KylerBurke** [comment]
First thought that comes to mind then:
- Add a `cables.yaml` file to the initializers directory that just says `cable_interfaces: true`, or it could even be blank.
- Check for existence of the file in this startup script and bail if the file doesn't exist

Since this startup script is unique to us, it's highly unlikely we'll ever encounter a `cables.yaml` initializer file unintentionally.
Could add a yaml safe_load to check for the key: boolean value as an extra precaution, but that might be overkill. 

So yeah, first idea for a sane "go/no-go" check in this startup script is the existence of a supporting file. Netbox seems to have no "environment" context provided to the application. (i.e. dev/preview/prod). We could make it key off a environment variable `CABLE_INTERFACES_AT_STARTUP` or something, and declare that in dev & preview cloud-ops deployments as well as this repo's docker-compose file. But we currently aren't setting any ENV context in cloud-ops so it would be a ❄️ 

Having no `/manifests` directory to define initializers, or excluding `cables.yaml` from `/manifests/<env>-netbox-initializers.yaml` in cloud ops seems like the clearest path forward IMO.

@hoanhan101

**Comment by hoanhan101** [comment]
Just added a `cables.yml` file to the initializers directory that allows one to enable/disable the automated cabling. One question I have is that if we should set the config to false by default in this PR. Another is whether there is a place to document this process.

**Comment by KylerBurke** [comment]
I would set it to `true` for default, that way you don't have to modify your local branch for development. It seems like a nice-to-have feature for all deploys via docker-compose. Not to mention there's the additional failsafe of not executing if the file isn't present at all.

**Comment by hoanhan101** [comment]
I agree that having it set to `true` by defaults will save us a ton of time configuring and the process itself is pretty much self-documenting. However, one thing that I am worried about is that the script should only be run once, not every time at the start. Since a cable is made up of distinct interfaces, re-cabling them would give us unique key validation errors.

In a normal dev workflow where we work with `docker-compose` to bring up/tear down these containers often, we might want to have it set to `false` most of the time and only `true` when needed. Unless we remove the volumes associated with these containers every time we bring it down, then we can set it to `true` all the time.

**Comment by KylerBurke** [comment]
To be honest, my workflow with this project has primarily been messing with the initializers. So I defer to your judgement, having repeatedly used the docker-compose command for situations other than testing the startup scripts. I suppose that does make sense then, to keep it as false so reoccurring deployments don't break the database. You'd have to explicitly enable cabling when you wanted to have that data.

**Pull request merged**
