### PR TITLE
Use site name in query for racks when building devices

### PR DESCRIPTION
**Pull request by KylerBurke**
This is working for my locally using the initializers I have staged for the Dev environment

### CODE REVIEW

**Review by marcoceppi — COMMENTED** [review]
Won't this leave `site` to be `None` each time? Since it gets pop'd during L38's loop?

**Comment by KylerBurke** [comment]
That's what I thought too, but if you look at L42, it puts the complete object right back into the params dict. Using the built object in the query seems to work just fine, I've run the initializers a couple dozen times today and it looks to be creating all the records successfully

**Comment by KylerBurke** [comment]
image

**Comment by marcoceppi** [comment]
Ah, I see. Very clever!

**Review by marcoceppi — APPROVED** [review]

**Pull request merged**
