### PR TITLE
Create configuration.py

### PR DESCRIPTION
**Pull request by jinaloo7**
patch for the configuration file missing error

### CODE REVIEW

**Comment by marcoceppi** [comment]
I don't think this belongs here. What problem are you trying to solve?

**Comment by jinaloo7** [comment]
When running docker-compose up after cloning the repo it asks for `config.py `file which is missing and due to that netbox is not booting up.I am trying to resolve that error.

**Comment by marcoceppi** [comment]
yeah, it's just something you have to do as a one time item. It's currently in the gitignore file for a reason. The long story short is because of how we do the docker builds and the local mount bind into docker the configuration.py file gets overwritten. I'd rather just document the steps to do a local setup than to commit this file into the repo

**Comment by marcoceppi** [comment]
Basically, copy `docker/configuration.docker.py` to `netbox/netbox/configuration.py` but don't commit it to the repo. That should unblock you locally

**Pull request closed without merging**
